In [1]:
import numpy as np

In [4]:
a=np.random.randint(1,9, size=(3,3))
a

array([[2, 4, 8],
       [4, 8, 5],
       [8, 7, 7]])

In [5]:
a.tolist()

[[2, 4, 8], [4, 8, 5], [8, 7, 7]]

In [6]:
a.trace()

17

In [9]:
a.shape

(3, 3)

In [12]:
s=0
for i in range(min(a.shape)):
    s=s + a[i, i]
s

17

In [28]:
a

array([[2, 4, 8],
       [4, 8, 5],
       [8, 7, 7]])

In [14]:
a[a>2]

array([4, 8, 4, 8, 5, 8, 7, 7])

In [27]:
b =np.random.randint(1,9, size=(3,3))
b

array([[6, 5, 7],
       [8, 5, 6],
       [8, 7, 5]])

In [18]:
a.shape == b.shape

True

In [19]:
l,c=a.shape

In [20]:
l

3

In [29]:
l=3
c=np.zeros(a.shape)
for i in range(l):
   for j in range(l): 
    c[i,j]=a[i,j]+b[i,j]
print(c)
    

[[ 8.  9. 15.]
 [12. 13. 11.]
 [16. 14. 12.]]


In [33]:
a.mean(axis=0)

array([4.66666667, 6.33333333, 6.66666667])